# GlobalPost Configuration

# Database settings
database:
  type: sqlite  # sqlite or mysql
  sqlite:
    file: globalpost.db
  mysql:
    host: localhost
    port: 3306
    database: globalpost
    username: root
    password: password

# Server identification
server:
  name: server1

# Channel configuration (which servers can send mail to each other)
channels:
  server1:
    - server2
    - server3
  server2:
    - server1
  server3:
    - server1

# Item blacklist (items that cannot be sent through mail)
blacklist:
  items:
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - PINK_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - RED_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - ENCHANTED_BOOK
    - BEDROCK

# Mail system settings
settings:
  max_items_per_mail: 27
  max_mails_per_player: 50
  mail_expiry_days: 30
  enable_local_mail: true  # Allow same-server mail when MySQL not configured

# Sound settings
sounds:
  enabled: true
  gui_open: "UI_BUTTON_CLICK"
  mail_send: "ENTITY_PLAYER_LEVELUP"
  mail_receive: "BLOCK_NOTE_BLOCK_BELL"
  volume: 1.0
  pitch: 1.0

# GUI Customization
gui:
  mailbox:
    title: "§6§lMailbox"
    player_head_slot: 4
    # Content slots (where mail items are displayed)
    content_slots: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]
    # Pagination and control slots
    previous_page_slot: 46
    next_page_slot: 52
    refresh_slot: 50
    send_mail_slot: 49
  sendmail:
    title: "§6§lSend Mail to {recipient}"
    player_head_slot: 4
    content_slots: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]
    send_button_slot: 48
    message_button_slot: 49
    cancel_button_slot: 45

# Message system
messages:
  enabled: true
  max_length: 255
  timeout_seconds: 30