name: GlobalPost
version: '1.0'
main: org.anonventions.globalPost.GlobalPost
api-version: '1.20'
load: STARTUP
authors: [ Axmon, amon_m, anonventions ]
description: Wardrobe is a plugin for saving and managing skins!
website: https://github.com/Anonventions
